---
abstract: 'Enable error and status logging in Catalyst Models via Log::Any'
author:
  - unknown
build_requires:
  File::Basename: 0
  File::Spec: 0
  Test::More: 0.87
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-Adapter-Catalyst
provides:
  Log::Any::Adapter::Catalyst:
    file: lib/Log/Any/Adapter/Catalyst.pm
    version: 0.10
requires:
  Carp: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Log-Any-Adapter-Catalyst
  homepage: https://metacpan.org/module/Log::Any::Adapter::Catalyst
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/log-any-catalyst
version: 0.10
